name: Planecart
main: kr.kkiro.projects.bukkit.planecart.bukkit.Planecart
version: 0.0.1
database: true
depend: [BKCommonLib]
commands:
  plane:
    description: Plane related commands.
    usage: "Usage: /<command>"
  planecart:
    description: Planecart main command.
    usage: "Usage: /<command>"
metrics: true